# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Research Software Citation
name: Stephan Druskat
subtitle: Cite and Make Citable!
email: research
description: >- # this means to ignore newlines until "baseurl:"
  Software is an important research output. Cite it and make it citable!
twitter_username: stdruskat
github_username: sdruskat
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Stephan Druskat"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Pursuing a CS PhD on software citation."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://sdruskat.net"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/stdruskat"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sdruskat"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-open-text"
      url: "mailto:mail@research-software.org"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/stdruskat"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sdruskat"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      header:
        og_image: /assets/images/og-image.jpg
        image: /assets/images/og-image.jpg

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
